title: Koshak Keyboard Layout
description: The Layout Designed for speed and balance
show_downloads: true
theme: jekyll-theme-midnight
github:
  zip_url: /Koshcher/koshak-layout/raw/main/download/koshak-layout-install.zip
google_analytics: G-3DER8V21NQ
