title: Koshak Layout
description: The Layout Designed for speed and balance
show_downloads: true
theme: jekyll-theme-midnight
github:
  zip_url: download/koshak-layout-all.zip
google_analytics: G-3DER8V21NQ
